"use server"

import { addPageToDatabaseType } from "@/types/types";
import { Client } from "@notionhq/client";

export const addPageToDatabase = async (args: addPageToDatabaseType) => {
  const notion = new Client({ auth: args.notionKey });
  const parentDatabaseId = args.notionUrl;
  console.log({ parentDatabaseId });
  const response = await notion.pages.create({
    icon: {
      type: "emoji",
      emoji: "✏️",
    },
    parent: {
      type: "database_id",
      database_id: parentDatabaseId,
    },
    properties: {
      Name: {
        title: [
          {
            text: {
              content: args.topic,
            },
          },
        ],
      },
    },

    //content generated by chatGpt
    children: [
      {
        object: "block",
        heading_2: {
          rich_text: [
            {
              text: {
                content: `Here's some important information about ${args.topic}`,
              },
            },
          ],
        },
      },

      {
        object: "block",
        paragraph: {
          rich_text: [
            {
              text: {
                content: args.content,
              },
            },
          ],
          color: "default",
        },
      },

      // summary generated by youtube and chatGpt

      {
        object: "block",
        heading_2: {
          rich_text: [
            {
              text: {
                content: `https://www.youtube.com/watch?v=${args.videoId}`,
              },
            },
          ],
        },
      },

      {
        object: "block",
        heading_2: {
          rich_text: [
            {
              text: {
                content: "here's a summary of the above video .",
              },
            },
          ],
        },
      },

      {
        object: "block",
        paragraph: {
          rich_text: [
            {
              text: {
                content: args.trancriptSummary,
                link: {
                  url: `https://www.youtube.com/watch?v=${args.videoId}`,
                },
              },
              //@ts-ignore
              href: `https://www.youtube.com/watch?v=${args.videoId}`,
            },
          ],
          color: "default",
        },
      },
    ],
  });
  console.log(response);
};
